@file:OptIn(ExperimentalWasmInterop::class)
@file:Suppress("FunctionName", "unused")
import kotlin.random.Random
fun interface Callback {
    fun callback(params: String?): String?
}

object WasmRouter {
    val handlers = mutableMapOf<String, Callback>()
    fun register(action: String, callback: Callback) {
        handlers[action] = callback
    }
    fun dispatch(action: String?, args: String?): String? {
        return handlers[action]?.callback(args)
    }
}



private fun initApp1(): () -> Unit = {
    WasmRouter.register("getUser") { jsonArgs -> jsonArgs }
    WasmRouter.register("add") { "{\"result\": 999}" }
    val number = Random.nextInt()
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
}

private fun initApp2(): () -> Unit = {
    WasmRouter.register("getUser") { jsonArgs -> jsonArgs }
    WasmRouter.register("add") { "{\"result\": 999}" }
    val number = Random.nextInt()
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
    WasmRouter.register("add$number") { "$number" }
}

private val init__ by lazy {
    initApp1()?.invoke()
    initApp2()?.invoke()
}

@WasmExport
fun WasmEntry() { WasmRouter.dispatch("inita", "123") }

fun main() {
    val value = Random.nextInt()
    WasmRouter.register("init") {
        initApp1()?.invoke()
        initApp2()?.invoke()
        "asdasd $value  "
    }
}